### PR TITLE
Expenses reimbursement policy updated

### PR DESCRIPTION
**Pull request by idvoretskyi**
As discussed with @caniszczyk.

cc @taylorwaggoner

### CODE REVIEW

**Comment by chris-short** [comment]
Seems totally reasonable to me.

**Comment by caniszczyk** [comment]
thanks @chris-short, I'll update the PR to mention that we can make exceptions if asked, but we have to be careful about budget as we continue to scale our community

**Comment by idvoretskyi** [comment]
@caniszczyk updated :)

**Comment by InAnimaTe** [comment]
This also sounds reasonable to me. I should have commented earlier but specifying a date this goes into effect would be helpful, especially for some of us who have already planned to have the original amount for May (I'm sure we'll still honor for this month?)

**Comment by rosskukulinski** [comment]
Seconded what @InAnimaTe says - I still need to submit my April meetup expense, and the May event is Monday and the order has already been placed.

**Pull request merged**
